# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

# extra settings to be merged into OpenTelemetry Collector configuration
# do not delete this file

## Example configuration for sending data to your own OTLP HTTP backend
## Note: the spanmetrics exporter must be included in the exporters array
## if overriding the traces pipeline.
##
#  exporters:
#    otlphttp/example:
#      endpoint: <your-endpoint-url>
#
#  service:
#    pipelines:
#      traces:
#        exporters: [spanmetrics, otlphttp/example]

connectors:
  spanmetrics:
    dimensions:
      - name: app.product.id
      - name: flag.productCatalogTimeout
      - name: app.cache_hit
      - name: app.recommendation.cache_enabled
    dimensions_cache_size: 1000
    aggregation_temporality: "AGGREGATION_TEMPORALITY_CUMULATIVE"
    metrics_flush_interval: 15s

exporters:
  newrelic:
    endpoint: "https://otlp.nr-data.net:443"
    headers:
      api-key: "106259f4551345ece679eaf8abf1e7c6FFFFNRA"

service:
  pipelines:
    logs:
      receivers: [newrelic]
      processors: [batch]
      exporters: [newrelic]
